(() => {
  const root = document.querySelector('#sd-config-root');
  if (!root) return;
  const eur = new Intl.NumberFormat('nl-BE',{style:'currency',currency:'EUR',maximumFractionDigits:0});
  const data = {
    model:[['barrel','Barrel Sauna','Authentieke ronde vorm · snel warm',3450,'barrel-5.png'],['cube','Cube Sauna','Strak design · extra binnenruimte',4450,'cube-1.png'],['hottub','Hot Tub','Houtgestookt buitenbad · elk seizoen',3500,'hottub-1.png']],
    size:[['2m','2 meter',0],['2.5m','2,5 meter',400],['3m','3 meter',800],['3.5m','3,5 meter',1200],['4m','4 meter',1600],['5m','5 meter',2400]],
    material:[['standard','Standaard hout',0],['thermowood','Thermowood upgrade',800],['diy','DIY-kit',-500]],
    heater:[['m90','Harvia M90 · elektrisch',0],['cilindro','Harvia Cilindro · elektrisch',250],['m3','Harvia M3 · houtgestookt',300],['stoveman','Stoveman 13 · houtgestookt',450]],
    glass:[['none','Standaard deur',0],['doorGlass','Deur met raam',250],['rearHalf','Halfwand-raam',480],['rearFull','Volledige glaswand',950]],
    finish:[['natural','Natuurlijke afwerking',0],['black','Zwart gebeitst',200],['brown','Bruin gebeitst',200],['bench','Ergonomische rugleuningen',180]],
    delivery:[['delivery','Levering op locatie',0],['install','Levering & montage',650],['access','Moeilijke toegang / kraanbespreking',0]]
  };
  const steps=[['model','Model','Kies je wellnessmodel','Start bij de vorm die bij je tuin of project past.'],['size','Formaat','Kies de afmeting','Je ziet de prijs direct mee evolueren.'],['material','Materiaal','Kies je houtpakket','Thermowood is de duurzame premium upgrade.'],['heater','Kachel','Kies je warmtebron','Elektrisch of de authentieke houtvuurbeleving.'],['glass','Glas & indeling','Kies licht en privacy','Maak de sauna helemaal van jou.'],['finish','Afwerking','Kies de details','Bescherming, kleur en comfort.'],['delivery','Levering','Kies je service','Wij stemmen levering en montage met je af.'],['quote','Offerte','Bijna klaar','Laat je gegevens achter voor een persoonlijke, correcte offerte.']];
  const state={model:'cube',size:'2m',material:'standard',heater:'m90',glass:'none',finish:'natural',delivery:'delivery',step:0};
  const choice=(key)=>data[key]?.find(x=>x[0]===state[key])||['','',0];
  const price=()=>steps.slice(0,7).filter(([key])=>state.model!=='hottub'||['model','delivery'].includes(key)).reduce((sum,[key])=>sum+(Number(choice(key)[3] ?? choice(key)[2])||0),0);
  const model=()=>choice('model');
  const visibleSteps=()=>state.model==='hottub'?steps.filter(s=>!['size','material','heater','glass','finish'].includes(s[0])):steps;
  function line(label,value){return `<span><b>${label}</b><i>${value}</i></span>`}
  function renderSummary(){ const m=model(); const labels=[['Model',m[1]],['Formaat',choice('size')[1]],['Materiaal',choice('material')[1]],['Kachel',choice('heater')[1]],['Glas',choice('glass')[1]],['Afwerking',choice('finish')[1]],['Service',choice('delivery')[1]]]; return `<aside class="sd-summary"><div class="sd-kicker">Live configuratie</div><h3>Jouw Steam Dream</h3><img class="sd-image" src="${m[4]}" alt="${m[1]}"><div class="sd-total">${eur.format(price())}</div><div class="sd-lines">${labels.filter((_,i)=>state.model!=='hottub'||[0,6].includes(i)).map(x=>line(x[0],x[1])).join('')}</div><p class="sd-kicker" style="margin-top:18px">Geen voorschot · prijs incl. btw</p></aside>` }
  function options(key){return `<div class="sd-options">${data[key].map(item=>`<button type="button" class="sd-option ${state[key]===item[0]?'is-selected':''}" data-choice="${key}" data-value="${item[0]}">${key==='model'?`<img src="${item[4]}" alt="${item[1]}">`:''}<strong>${item[1]}</strong><small>${item[2]||''}</small><em>${Number(item[3]||item[2]||0)===0?'Inbegrepen':(Number(item[3]||item[2])>0?'+':'')+eur.format(Number(item[3]||item[2]))}</em></button>`).join('')}</div>`}
  function quote(){return `<form class="sd-form" id="sd-quote-form"><label>Voornaam<input required name="name" autocomplete="given-name"></label><label>E-mail<input required type="email" name="email" autocomplete="email"></label><label class="full">Telefoon<input name="phone" autocomplete="tel"></label><label>Postcode<input required name="postcode" autocomplete="postal-code"></label><label>Land<input required name="country" value="België"></label><label class="full">Vertel kort over je tuin of project<textarea name="note" placeholder="Bijvoorbeeld gewenste leverperiode, toegang tot de tuin of vragen."></textarea></label><button class="sd-btn primary full" type="submit">Vraag mijn persoonlijke offerte aan</button><p class="full sd-note">Je ontvangt een persoonlijke offerte; de definitieve prijs hangt af van levering, montage en bereikbaarheid.</p></form>`}
  function render(){const active=visibleSteps(); if(state.step>=active.length)state.step=active.length-1; const step=active[state.step]; const [key,label,title,copy]=step; root.innerHTML=`<div class="sd-config"><div class="sd-shell"><main><div class="sd-tabs" role="tablist">${active.map((s,i)=>`<button type="button" class="sd-tab ${i===state.step?'is-active':''}" data-step="${i}"><span>${i+1}</span>${s[1]}</button>`).join('')}</div><section class="sd-panel"><div class="sd-step-head"><div><h3>${title}</h3><p>${copy}</p></div><span class="sd-counter">${state.step+1} / ${active.length}</span></div>${key==='quote'?quote():options(key)}${key!=='quote'?`<div class="sd-nav"><button class="sd-btn secondary" type="button" data-nav="prev" ${state.step===0?'disabled':''}>← Vorige</button><button class="sd-btn primary" type="button" data-nav="next">${state.step===active.length-1?'Naar offerte':'Volgende stap →'}</button></div>`:''}</section></main>${renderSummary()}</div></div>`; bind();}
  function bind(){root.querySelectorAll('[data-choice]').forEach(el=>el.addEventListener('click',()=>{state[el.dataset.choice]=el.dataset.value;if(el.dataset.choice==='model'&&el.dataset.value==='hottub'){state.delivery='delivery';state.step=1}render()}));root.querySelectorAll('[data-step]').forEach(el=>el.addEventListener('click',()=>{state.step=Number(el.dataset.step);render()}));root.querySelector('[data-nav="prev"]')?.addEventListener('click',()=>{state.step--;render()});root.querySelector('[data-nav="next"]')?.addEventListener('click',()=>{state.step++;render()});root.querySelector('#sd-quote-form')?.addEventListener('submit',submit)}
  function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);const selected=steps.slice(1,7).filter(([k])=>state.model!=='hottub'||k==='delivery').map(([k,l])=>`${l}: ${choice(k)[1]}`).join('\n');const summary=`Aanvraag Steam Dream\n\nModel: ${model()[1]}\nConfiguratie:\n${selected}\nGeschatte prijs: ${eur.format(price())}\n\nNaam: ${f.get('name')}\nE-mail: ${f.get('email')}\nTelefoon: ${f.get('phone')}\nPostcode: ${f.get('postcode')}, ${f.get('country')}\nOpmerking: ${f.get('note')}`;window.location.href=`mailto:info@steamdreamsaunas.com?subject=${encodeURIComponent('Offerteaanvraag '+model()[1])}&body=${encodeURIComponent(summary)}`;}
  window.selectModel=(value)=>{if(data.model.some(x=>x[0]===value)){state.model=value;state.step=0;render();document.querySelector('#contact')?.scrollIntoView({behavior:'smooth'})}};render();
})();
